name: QA Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  api-tests:
    name: API Testing (Postman + Newman)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api-testing
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Flask and other dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install flask

      - name: Install Newman
        run: npm install -g newman

      - name: Verify Flask installation
        run: |
          python3 -m pip show flask

      - name: Start mock API server
        run: |
          nohup python3 mock_api_server.py &
          sleep 3

      - name: Run API tests
        run: |
          mkdir -p reports
          bash run.sh

      - name: Upload API test reports
        uses: actions/upload-artifact@v4
        with:
          name: newman-report
          path: reports/

  ui-tests:
    name: UI Automation (Playwright)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ui-automation
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci || npm install

      - name: Start mock UI server
        run: |
          nohup node playwright/mock_ui_server.js &
          sleep 3

      - name: Run Playwright tests
        run: |
          npx playwright install --with-deps
          npx playwright test

      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
